openapi: 3.0.1
info:
  title: Intent
  version: version not set
externalDocs:
  description: Find our official documentation in the MessageBird Docs
  url: https://developers.messagebird.com/api
servers:
- url: https://intent.messagebird.com/
tags:
- name: Intent
  description: "The MessageBird Intent API enables predicting intents from a given\
    \ phrase using a machine learning model that was trained on one of your datasets.\
    \ Datasets can be created and managed using the [dataset section of the MessageBird\
    \ Dashboard](https://dashboard.messagebird.com/knowledge-base/list). \n\nIntent\
    \ recognition is a way to group the phrases from incoming messages. For example,\
    \ `\"hi\"` and `\"hello\"` are both ways to express a greeting. The corresponding\
    \ intent would be `greeting`. You might also want to define a `book-room` intent\
    \ that might be phrased as: `\"Can I book a room for tomorrow?\"` or `\"do you\
    \ have any vacancies?\"`. The MessageBird Intent API applies machine learning\
    \ to generalize from the phrases that you added to your intents so that unseen\
    \ phrases are automatically mapped to the right intent. You can use this to route\
    \ your messages based on their topic, or build an intelligent IVR menu that can\
    \ deal with natural language, or integrate this into your chatbot system. The\
    \ possibilities are endless! \n\nYou can configure the intents you want to recognize\
    \ through the [datasets section of the dashboard](https://dashboard.messagebird.com/knowledge-base/list).\
    \ You can easily improve your intent recognition accuracy by using the Train UI\
    \ that can be accessed from the [dataset overview](https://dashboard.messagebird.com/knowledge-base/list)."
paths:
  /api/v1/datasets:
    get:
      tags:
      - Intent
      summary: list datasets
      description: "Lists datasets containing intents and corresponding phrases. You\
        \ can choose to list only your own datasets, as well as template datasets,\
        \ or both. Template datasets are used as examples and can be found under the\
        \ `Templates` tab in the [dataset overview of the dashboard](https://dashboard.messagebird.com/knowledge-base/list).\
        \ You can clone such datasets to kickstart the creation of a dataset that\
        \ is tailored to your use-case. \n\nNote that the results are paginated and\
        \ so you might need to iteratively call this endpoint to obtain all your datasets."
      operationId: Intent_ListDatasets
      parameters:
      - name: listMode
        in: query
        description: |-
          List mode indicating to query template datasets, only user datasets or both.

           - ALL: List all datasets.
           - ONLY_TEMPLATE: List the template datasets. Template datasets are used as examples and can be found under the `Templates` tab in the [dataset overview of the dashboard](https://dashboard.messagebird.com/knowledge-base/list). You can clone such datasets to kickstart the creation of a dataset that is tailored to your use-case.
           - ONLY_USER: List the user datasets.
        schema:
          type: string
          default: ALL
          enum:
          - ALL
          - ONLY_TEMPLATE
          - ONLY_USER
        example: ONLY_USER
      - name: limit
        in: query
        description: The limit defining the maximal number of datasets to return.
        schema:
          type: integer
          format: int64
          default: 20
      - name: cursor
        in: query
        description: "The cursor to view the next paginated collection of datasets\
          \ as provided by the `next_cursor` value in the [`ListDatasetsResponse`](#listdatasetsresponse-object)."
        schema:
          type: string
          default: "null"
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1ListDatasetsResponse'
        "401":
          description: Returned when the user is not authorized.
          content:
            application/json:
              schema:
                type: object
        "404":
          description: Returned when the resource does not exist.
          content:
            application/json:
              schema:
                type: object
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      security:
      - AccessKey: []
  /api/v1/datasets/{datasetId}:
    get:
      tags:
      - Intent
      summary: "Get description of a model, model can still be in training and not\
        \ available for predictions"
      description: "Retrieves the dataset for the given dataset ID. It only displays\
        \ the metadata corresponding to the dataset. If you want to view the individual\
        \ intent phrases that you have added, you can use the [dataset section of\
        \ the dashboard](https://dashboard.messagebird.com/knowledge-base/list)."
      operationId: Intent_GetDataset
      parameters:
      - name: datasetId
        in: path
        description: "Unique ID for the dataset. You can obtain the IDs either from\
          \ the [dataset section in the dashboard](https://dashboard.messagebird.com/knowledge-base/list)\
          \ or by listing the datasets with the Intent API."
        required: true
        schema:
          type: string
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1Dataset'
        "401":
          description: Returned when the user is not authorized.
          content:
            application/json:
              schema:
                type: object
        "404":
          description: Returned when the resource does not exist.
          content:
            application/json:
              schema:
                type: object
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      security:
      - AccessKey: []
  /api/v1/datasets/{datasetId}/predict:
    post:
      tags:
      - Intent
      summary: Predict an intent for a phrase given a dataset
      description: "Predicts an intent for a phrase given a dataset ID. The Intent\
        \ API uses machine learning to generalize from the intents and phrases in\
        \ the dataset that was created in the [datasets overview](https://dashboard.messagebird.com/knowledge-base-list)\
        \ to infer the intent of the given `phrase`. Requires the active model for\
        \ the dataset to be trained. \n\nTraining a model usually takes around 1 after\
        \ a dataset is created or updated. This endpoint yields an error if the model\
        \ has not been trained yet."
      operationId: Intent_PredictIntent
      parameters:
      - name: datasetId
        in: path
        description: The unique ID that identifies the dataset for which a prediction
          should be made.
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              title: PredictIntentRequest
              type: object
              properties:
                phrase:
                  title: Phrase
                  type: string
                  description: The phrase that might contain an intent.
                  example: I'd like to order something
              description: A request for predicting an intent from a phrase and a
                dataset ID.
              example:
                phrase: I'd like to order something
        required: true
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1PredictIntentResponse'
        "401":
          description: Returned when the user is not authorized.
          content:
            application/json:
              schema:
                type: object
        "404":
          description: Returned when the resource does not exist.
          content:
            application/json:
              schema:
                type: object
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      security:
      - AccessKey: []
      x-codegen-request-body-name: body
  /api/v1/supported-languages:
    get:
      tags:
      - Intent
      summary: Get supported languages.
      description: Lists the languages supported by the Intent API.
      operationId: Intent_ListSupportedLanguages
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1LanguageList'
        "401":
          description: Returned when the user is not authorized.
          content:
            application/json:
              schema:
                type: object
        "404":
          description: Returned when the resource does not exist.
          content:
            application/json:
              schema:
                type: object
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      security:
      - AccessKey: []
components:
  schemas:
    protobufAny:
      type: object
      properties:
        '@type':
          type: string
      additionalProperties:
        type: object
    rpcStatus:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/protobufAny'
    v1Dataset:
      title: Dataset
      type: object
      properties:
        datasetId:
          title: Dataset Id
          type: string
          description: The unique ID for the dataset.
          format: uuid
          example: dde4eeae-7652-4bc8-8be1-1cd6ac898dc7
        intents:
          title: Intents
          type: array
          description: The collection of intents that were added to this dataset.
          example:
          - order
          - reservation
          items:
            type: string
        isTemplate:
          title: Is Template
          type: boolean
          description: "Describes if this dataset is a template dataset or not. Template\
            \ datasets are used as examples and can be found under the `Templates`\
            \ tab in the [dataset overview of the dashboard](https://dashboard.messagebird.com/knowledge-base/list).\
            \ You can clone such datasets to kickstart the creation of a dataset that\
            \ is tailored to your use-case."
          readOnly: true
          example: false
        name:
          title: Name
          type: string
          description: "The name of the dataset. You can configure the name once creating\
            \ a dataset in the [dashboard](https://dashboard.messagebird.com/knowledge-base/list)."
          example: My awesome dataset
        createdAt:
          title: Created At
          type: string
          description: "The timestamp of dataset creation. Uses the [ISO-8601 standard](https://en.wikipedia.org/wiki/ISO_8601)."
          format: timestamp
          readOnly: true
          example: 2021-08-24T12:04:32Z
        updatedAt:
          title: Updated At
          type: string
          description: "The timestamp of last update. Uses the [ISO-8601 standard](https://en.wikipedia.org/wiki/ISO_8601)."
          format: timestamp
          readOnly: true
          example: 2021-08-24T12:04:32Z
        description:
          title: Description
          type: string
          description: The optional description of the dataset.
          example: This dataset is clearly some awesome dataset.
        lastTrainedAt:
          title: Last Trained At
          type: string
          description: "The timestamp of last model that completed training. Uses\
            \ the [ISO-8601 standard](https://en.wikipedia.org/wiki/ISO_8601). If\
            \ there is not a model trained already, this field will not be populated."
          format: timestamp
          readOnly: true
          example: 2021-08-24T12:04:32Z
      description: "A collection of phrases with the corresponding intents. There\
        \ can be multiple matching phrases per intent. To inspect the phrases that\
        \ were added, go to the [datasets section in the dashboard](https://dashboard.messagebird.com/knowledge-base/list)."
      example:
        createdAt: 2021-08-24T12:04:32Z
        datasetId: dde4eeae-7652-4bc8-8be1-1cd6ac898dc7
        description: This dataset is clearly some awesome dataset.
        intents:
        - order
        - reservation
        isTemplate: false
        lastTrainedAt: 2021-08-24T12:04:32Z
        name: My awesome dataset
        updatedAt: 2021-08-24T12:04:32Z
    v1Language:
      title: Language
      type: object
      properties:
        iso6393Code:
          title: Iso 639 3 Code
          type: string
          description: The ISO-639-3 code of the language.
          example: nld
        name:
          title: Name
          type: string
          description: The English name of the language.
          example: Dutch
        languageCode:
          $ref: '#/components/schemas/v1LanguageCode'
      description: Language that was detected from the given phrase.
      example:
        iso6393Code: nld
        languageCode: NLD
        name: Dutch
    v1LanguageCode:
      type: string
      description: "Language code in ISO639-3 format. More info can be found here:\
        \ https://iso639-3.sil.org/code_tables/639/data."
      default: LANGUAGE_INVALID
      enum:
      - LANGUAGE_INVALID
      - LANGUAGE_UNDETERMINED
      - ENG
      - RUS
      - DEU
      - FRA
      - ITA
      - JPN
      - SPA
      - CEB
      - TUR
      - POR
      - UKR
      - EPO
      - POL
      - SWE
      - NLD
      - HEB
      - ZHO
      - HUN
      - ARA
      - CAT
      - FIN
      - CES
      - FAS
      - SRP
      - ELL
      - VIE
      - BUL
      - KOR
      - NOR
      - MKD
      - RON
      - IND
      - THA
      - HYE
      - DAN
      - TAM
      - HIN
      - HRV
      - HBS
      - BEL
      - KAT
      - TEL
      - KAZ
      - WAR
      - LIT
      - GLG
      - SLK
      - BEN
      - EUS
      - SLV
      - KAN
      - MAL
      - MAR
      - EST
      - AZE
      - MSA
      - SQI
      - LAT
      - BOS
      - NNO
      - URD
      - LAV
      - MYA
      - TAT
      - AFR
      - OCI
      - NDS
      - KIR
      - AST
      - TGL
      - ISL
      - INA
      - SIN
      - GUJ
      - KHM
      - BRE
      - BAK
      - UZB
      - BOD
      - PAN
      - VOL
      - ALS
      - NEP
      - CYM
      - JBO
      - FRY
      - MON
      - LTZ
      - CHE
      - UIG
      - TGK
      - SCO
      - SAN
      - CHV
      - JAV
      - MIN
      - IDO
      - ORI
      - ASM
      - NEW
      - GLE
      - MLG
      - ARG
      - CKB
      - SWA
      - BAR
      - LMO
      - YID
      - ARZ
      - MHR
      - AZB
      - SAH
      - PNB
      - SUN
      - BPY
      - PMS
      - ILO
      - WUU
      - KUR
      - PUS
      - ILE
      - XMF
      - YUE
      - GOM
      - LIM
      - MWL
      - COR
      - SND
      - HSB
      - SCN
      - GLA
      - PAM
      - BHO
      - MAI
      - VEC
      - MLT
      - DIV
      - WLN
      - MZN
      - AMH
      - QUE
      - CBK
      - TUK
      - ROH
      - OSS
      - VLS
      - YOR
      - LAO
      - LEZ
      - SOM
      - MYV
      - DIQ
      - MRJ
      - DSB
      - FRR
      - HAT
      - GRN
      - BXR
      - KOM
      - SRD
      - KRC
      - BCL
      - NAP
      - GLV
      - AVA
      - RUE
      - XAL
      - PFL
      - DTY
      - HIF
      - COS
      - LRC
      - VEP
      - TYV
      - NOB
      - SNA
      - KIN
      - IBO
      - SMO
      - SOT
      - MRI
      - WOL
      - XHO
      - HAU
      - HAW
      - NYA
      - ZUL
      - HMN
    v1LanguageList:
      title: LanguageList
      type: object
      properties:
        languages:
          title: Languages
          type: array
          description: The collection of languages.
          example:
          - iso6393Code: nld
            languageCode: NLD
            name: Dutch
          - iso6393Code: eng
            languageCode: ENG
            name: English
          - iso6393Code: spa
            languageCode: SPA
            name: Spanish
          - iso6393Code: zho
            languageCode: ZHO
            name: Chinese
          items:
            $ref: '#/components/schemas/v1Language'
      description: List of recognized languages.
      example:
        languages:
        - iso6393Code: nld
          languageCode: NLD
          name: Dutch
        - iso6393Code: eng
          languageCode: ENG
          name: English
        - iso6393Code: spa
          languageCode: SPA
          name: Spanish
        - iso6393Code: zho
          languageCode: ZHO
          name: Chinese
    v1ListDatasetMode:
      type: string
      description: Mode for listing datasets.
      default: ALL
      enum:
      - ALL
      - ONLY_TEMPLATE
      - ONLY_USER
    v1ListDatasetsResponse:
      title: ListDatasetsResponse
      type: object
      properties:
        datasets:
          title: Datasets
          type: array
          description: "The (paginated) collection of datasets. This can contain both\
            \ your own datasets as well as template datasets. Template datasets are\
            \ used as examples and can be found under the `Templates` tab in the [dataset\
            \ overview of the dashboard](https://dashboard.messagebird.com/knowledge-base/list).\
            \ You can clone such datasets to kickstart the creation of a dataset that\
            \ is tailored to your use-case."
          example:
          - createdAt: 2021-08-24T12:04:32Z
            datasetId: dde4eeae-7652-4bc8-8be1-1cd6ac898dc7
            description: This dataset is clearly some awesome dataset.
            intents:
            - order
            - reservation
            isTemplate: false
            lastTrainedAt: 2021-08-24T12:04:32Z
            name: My awesome dataset
            updatedAt: 2021-08-24T12:04:32Z
          items:
            $ref: '#/components/schemas/v1Dataset'
        limit:
          title: Limit
          type: integer
          description: "The effective limit of the maximum number of datasets that\
            \ could be returned by the list endpoint. If the `limit` defined in [`ListDatasetsRequest`](#listdatasetsrequest-object)\
            \ was not set, this value indicates the used limit."
          format: int64
          example: 20
        nextCursor:
          title: Next Cursor
          type: string
          description: The cursor that can be used to obtain the next paginated collection
            of datasets.
          example: VGhpcyBpcyBub3QgYSByZWFsIGN1cnNvciwgYnV0IHRoZXkgd291bGQgYmUgYmFzZTY0IGVuY29kZWQgdG9vCg==
      description: A response containing the Intent datasets that were queried.
      example:
        datasets:
        - createdAt: 2021-08-24T12:04:32Z
          datasetId: dde4eeae-7652-4bc8-8be1-1cd6ac898dc7
          description: This dataset is clearly some awesome dataset.
          intents:
          - order
          - reservation
          isTemplate: false
          lastTrainedAt: 2021-08-24T12:04:32Z
          name: My awesome dataset
          updatedAt: 2021-08-24T12:04:32Z
        limit: 20
        nextCursor: VGhpcyBpcyBub3QgYSByZWFsIGN1cnNvciwgYnV0IHRoZXkgd291bGQgYmUgYmFzZTY0IGVuY29kZWQgdG9vCg==
    v1PredictIntentResponse:
      title: PredictIntentResponse
      type: object
      properties:
        intent:
          title: Intent
          type: string
          description: The intent that is predicted for the given phrase.
          example: order
        intentPredicted:
          title: Intent Predicted
          type: boolean
          description: Boolean indicating an intent was predicted. If false the phrase
            could not be matched with an intent.
          example: true
      description: A response for predicting an intent from a phrase and a dataset
        ID.
      example:
        intent: order
        intentPredicted: true
  securitySchemes:
    AccessKey:
      type: apiKey
      name: Authorization
      in: header
x-original-swagger-version: "2.0"
